Auction_Bidding/Auction_Bidding.Web/Controllers/AuctionController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Auction_Bidding.Web.Data.Entities;
using Auction_Bidding.Web.Models;
using Auction_Bidding.Web.Repository;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace Auction_Bidding.Web.Controllers
{
    public class AuctionController : Controller
    {
        //resolving repository dependencies
        private IAuctionRepository _auctions = null;
        private IWebHostEnvironment _env = null;

        public AuctionController(IAuctionRepository auction, IWebHostEnvironment env)
        {
            _auctions = auction;
            _env = env;
        }

        
        //upload auction
       [Route("AddAuction")]
        public ViewResult uploadAuction(bool isSuccess = false,int auctionId = 0)
        {
            ViewBag.isSuccess = isSuccess;
            ViewBag.auctionId = auctionId;
            return View();   
        }

        [Route("AddAuction")]
        [HttpPost]
        public async Task<IActionResult> uploadAuction(AuctionModel model)
        {
                if (ModelState.IsValid)
            {
                //saving image 
                if (model.AuctionCoverPhoto != null)
                {
                    model.AuctionCoverPhotoURL = await SaveImage(model.AuctionCoverPhoto, "Auction/Images");
                    //Saved Success
                    int bookId = await _auctions.SaveAuction(model);
                    if(bookId > 0)
                    {
                        return RedirectToAction(nameof(uploadAuction), new { isSuccess = true, auctionId = bookId });
                    }
                }
                return RedirectToAction(nameof(uploadAuction), new { isSuccess = false });
            }
            return View();
        }

        private async Task<string> SaveImage(IFormFile model,string path)
        {
            //create a name of the photo
            string photoPath =path + Guid.NewGuid().ToString() + "_" + model.FileName;
            string serverPath = Path.Combine(_env.WebRootPath, photoPath);
            await model.CopyToAsync(new FileStream(serverPath, FileMode.Create));
            return "/" + photoPath;
        }

        //edit auction
        [HttpGet]
        [Route("UpdateAuction")]
        public async Task<IActionResult> UpdateAuction(int auctionId = 0 ,bool UpdateStatus = false)
        {
            AuctionModel auctionModel =  await _auctions.GetAuction(auctionId);
            bool isAjaxCall = HttpContext.Request.Headers["x-requested-with"] == "XMLHttpRequest";
            if (isAjaxCall)
            {
                return PartialView(auctionModel);
            }


            return View(auctionModel);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateAuction(AuctionModel model)
        {
            var isAjaxCall = HttpContext.Request.Headers["x-requested-with"] == "XMLHttpRequest";
            if (ModelState.IsValid)
            {
                bool status = await _auctions.UpdateAuction(model);
                if (status)
                {
                    if (isAjaxCall)
                    {
                        return Json(new { isValid = true, html = Helper.RenderRazorViewToString(this,"getAllAuction",await _auctions.GetAuctionsList() )});
                    }
                    return RedirectToAction(nameof(getAllAuction), new { updateStatus = true, auctionId = model.AuctionID });
                }
                if (isAjaxCall)
                {
                    return Json(new { isValid = false, html = Helper.RenderRazorViewToString(this, "UpdateAuction", await _auctions.GetAuctionsList()) });
                }
                return RedirectToAction(nameof(UpdateAuction), new { updateStatus = false, auctionId = model.AuctionID });

            }
            if (isAjaxCall)
            {
                return Json(new { isValid = false, html = Helper.RenderRazorViewToString(this, "UpdateAuction", await _auctions.GetAuctionsList()) });
            }
            return View();  
        }


        //get all auction
        [Route("Auctions")]
        public async Task<IActionResult> getAllAuction()
        {
            var isAjaxCall = HttpContext.Request.Headers["x-requested-with"] == "XMLHttpRequest";
            if (isAjaxCall)
            {
                return PartialView(await _auctions.GetAuctionsList());
            }
            return  View(await _auctions.GetAuctionsList());
        } 

        
        //delete auction
        public async Task<IActionResult> DeleteAuction(int auctionId)
        {
            bool isSuccess = await _auctions.DeleteAuction(auctionId);
            if (isSuccess){
                return Json(new { isSuccess = true, html = Helper.RenderRazorViewToString(this, "getAllAuction", await _auctions.GetAuctionsList() ) });
            }
            return Json(new { isSuccess = false,html = Helper.RenderRazorViewToString(this, "getAllAuction" , await _auctions.GetAuctionsList()) });
        }
    }
}

Auction_Bidding/Auction_Bidding.Web/Views/Auction/UpdateAuction.cshtml
@model AuctionModel
@{
    ViewData["Title"] = "UpdateAuction";
}
  <div class="container">
        <form method="post" enctype="multipart/form-data" asp-action="UpdateAuction" asp-controller="Auction" onsubmit="return jQueryUploadAuction(this);">
            <input asp-for="@Model.AuctionID" type="hidden" />
            <div class="form-group">
                <label asp-for="@Model.AuctionName"></label>
                <input asp-for="@Model.AuctionName" class="form-control" id="">
                <span asp-validation-for="@Model.AuctionName" class=""></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.AuctionPrice"></label>
                <input asp-for="@Model.AuctionPrice" class="form-control" id="">
                <span asp-validation-for="@Model.AuctionPrice"></span>
            </div>
            <div class="form-row">
                <div class="form-group">
                    <label asp-for="@Model.AuctionStartingDate"></label>
                    <input asp-for="@Model.AuctionStartingDate" class="form-control" id="">
                    <span asp-validation-for="@Model.AuctionStartingDate"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.AuctionEndingDate"></label>
                    <input asp-for="@Model.AuctionEndingDate" class="form-control" id="">
                    <span asp-validation-for="@Model.AuctionEndingDate"></span>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="@Model.Discription"></label>
                <input asp-for="@Model.Discription" class="form-control" id="">
            </div>
            <div class="form-group">
                <input type="submit" value="UploadBook" class="btn btn-primary btn-block" />
            </div>
        </form>
</div>

Auction_Bidding/Auction_Bidding.Web/Views/Auction/getAllAuction.cshtml
@model IEnumerable<AuctionModel>
@{ 
    ViewData["Title"] = "Auctions";
}
    <div id="view-all">
        <div class="container" >
            <div class="row">
                <div class="card-deck">
                    @foreach (AuctionModel auction in Model)
                    {
                        <partial name="_AuctionCard" model="auction" />
                    }
                </div>
            </div>
        </div>
    </div>

Auction_Bidding/Auction_Bidding.Web/Views/Auction/uploadAuction.cshtml
@model AuctionModel
@{

    ViewData["Title"] = "uploadAuction";
}

<div class="container">
    <h3 class="display-4">Add New Book</h3>
    <hr />

    @if (ViewBag.isSuccess == true)
    {
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <strong>Congratulations!</strong> Auction has been successfully Created<br />
            Click <a asp-route="UpdateAuction" asp-route-id="@ViewBag.auctionId">here</a> to view the details
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    }

    @* Upload Form *@
    <form method="post" enctype="multipart/form-data" asp-action="uploadAuction" asp-controller="Auction">
        <div class="form-group">
            <label asp-for="@Model.AuctionName"></label>
            <input asp-for="@Model.AuctionName" class="form-control" id="">
            <span asp-validation-for="@Model.AuctionName" class="text-danger"></span><br />
        </div>
        <div class="form-group">
            <label asp-for="@Model.AuctionPrice"></label>
            <input asp-for="@Model.AuctionPrice" class="form-control" id="">
            <span asp-validation-for="@Model.AuctionPrice" class="text-danger"></span><br />
        </div>
        <div class="form-group">
            <label asp-for="@Model.AuctionStartingDate"></label>
            <input asp-for="@Model.AuctionStartingDate" class="form-control" id="">
            <span asp-validation-for="@Model.AuctionStartingDate" class="text-danger"></span><br />
        </div>
        <div class="form-group">
            <label asp-for="@Model.AuctionEndingDate"></label>
            <input asp-for="@Model.AuctionEndingDate" class="form-control" id="">
            <span asp-validation-for="@Model.AuctionEndingDate" class="text-danger"></span><br />
        </div>
        <div class="form-group">
            <label asp-for="@Model.Discription"></label>
            <input asp-for="@Model.Discription" class="form-control" id="">
            <span asp-validation-for="@Model.Discription" class="text-danger"></span><br />
        </div>
        <div class="form-group">
            <label asp-for="@Model.AuctionCoverPhoto"></label>
            <input asp-for="@Model.AuctionCoverPhoto" class="form-control" id="">
        </div>
        <div class="form-group">
            <input type="submit" value="UploadBook" class="btn btn-primary" />
        </div>
    </form>
</div>